version: "1.0"
info:
  model: int-scaffold
packages:
- name: Sgh0804Project
  gitServerName: srcGithubCtrl_Arti
  gitUrl: https://github.com/ArtiKhareNew
  gitUsername: ArtiKhareNew
  gitBranch: main
- name: AzRepoMultiplyPackage
  gitServerName: srcCtrl_AzRepos_Arti
  gitUrl: https://dev.azure.com/ArtiKhare/AzRepoMultiplyPackage/_git
  gitUsername: ArtiKhare
  gitBranch: main
